# Generated by Django 5.0.14 on 2025-12-08 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True, help_text='When the booking was created')),
                ('appointment_date', models.DateField(help_text='Scheduled appointment date')),
                ('appointment_time', models.TimeField(blank=True, help_text='Scheduled appointment time (optional)', null=True)),
                ('patient_name', models.CharField(help_text='Patient full name at booking time', max_length=200)),
                ('patient_email', models.EmailField(help_text='Patient email at booking time', max_length=254)),
                ('patient_phone', models.CharField(help_text='Patient phone number', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or special requests from patient')),
                ('provider_notes', models.TextField(blank=True, help_text='Internal notes from provider')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price at booking time', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When the booking was confirmed', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the booking was completed', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the booking was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(help_text='The medical package booked', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='packages.package')),
                ('patient', models.ForeignKey(help_text='The patient who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(help_text='The healthcare provider', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='bookings_bo_patient_9fafc6_idx'), models.Index(fields=['provider', 'status'], name='bookings_bo_provide_c56754_idx'), models.Index(fields=['appointment_date'], name='bookings_bo_appoint_1a8453_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
