# Generated by Django 5.0.14 on 2026-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='documents',
            field=models.JSONField(blank=True, default=list, help_text='Private medical documents (Cloudinary public_ids; signed URL on read)'),
        ),
    ]
