# Generated by Django 5.0.14 on 2025-12-06 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('dental', 'Dental Care'), ('hair_transplant', 'Hair Transplant'), ('rhinoplasty', 'Rhinoplasty'), ('face_lift', 'Face Lift'), ('liposuction', 'Liposuction'), ('breast_augmentation', 'Breast Augmentation'), ('tummy_tuck', 'Tummy Tuck'), ('blepharoplasty', 'Blepharoplasty'), ('eye_surgery', 'Eye Surgery'), ('cardiology', 'Cardiology'), ('oncology', 'Oncology'), ('orthopedic', 'Orthopedic'), ('bariatric', 'Bariatric Surgery'), ('fertility', 'Fertility Treatment'), ('checkup', 'Health Checkup'), ('other', 'Other')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('duration', models.CharField(max_length=50)),
                ('includes', models.JSONField(default=list)),
                ('excludes', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='providers.provider')),
            ],
            options={
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
