# Generated by Django 5.0.14 on 2025-12-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(help_text='The favorited package', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='packages.package')),
                ('user', models.ForeignKey(help_text='The patient who favorited the package', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'package'], name='packages_fa_user_id_8fdb79_idx')],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
